### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by HongChenTW** [cdvel/fops-cli#2]
HI @cdvel , this is Hong from Trend Micro, thanks for your work and there is 1 improvement suggestion:

### checksum error handling

`fops` sub-command `checksum` calls panic If user doesn't pass algorithm flag, it would be better to show hint when algorithm is not provided.

```sh
./fops checksum -f assets/binary.dat
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11a2d5d]

goroutine 1 [running]:
fops-cli/cmd.GetChecksum(...)
	...
```

**Comment by cdvel** [comment]
Fair suggestion @HongChenTW, thanks -- Fixed via https://github.com/cdvel/fops-cli/commit/a3b888244d4e6ada070d09bd5416be6e0eca99e0
